import {
  Home,
  Phone,
  Users,
  UserPlus,
  ShieldCheck,
  Ambulance,
  MapPin,
  MessageCircle,
  Megaphone,
  Wrench,
  Truck,
  Pill,
  Calendar,
  FileText,
  Utensils,
  LayoutDashboard,
  ClipboardCheck,
  Building2,
  Mic,
  Video,
  BarChart3,
  Accessibility,
  Smartphone,
  Grid3x3,
  Stethoscope,
  Car,
  ShoppingCart,
  Hospital,
  Film,
  Landmark,
  Lightbulb,
  Music,
  Send,
  Fan,
  Camera,
  Gift,
} from 'lucide-react';

export type ShowcaseStatus = 'live' | 'planned';

export interface ShowcaseFeature {
  slug: string;
  number: number;
  phase: string;
  title: string;
  tagline: string;
  description: string;
  status: ShowcaseStatus;
  pattern: string;
  props: Record<string, unknown>;
}

export const SHOWCASE_FEATURES: ShowcaseFeature[] = [
  {
    slug: 'home-hub',
    number: 1,
    phase: 'A',
    title: 'Home hub',
    tagline: 'One screen, role-appropriate actions',
    description: 'The first thing everyone sees after signing in — a small set of large, unmistakable actions, tailored to whether you\'re the elder, a family member, an admin, or a provider.',
    status: 'live',
    pattern: 'tile-grid',
    props: {
      greeting: 'Hello, Kamala',
      tiles: [
        { icon: 'Phone', label: 'Call Family', sublabel: 'Reach saved contacts' },
        { icon: 'Users', label: 'Your Profile', sublabel: 'Update your details' },
        { icon: 'ShieldCheck', label: 'Need Help Now', sublabel: 'Emergency SOS', accent: 'danger' },
      ],
    },
  },
  {
    slug: 'emergency-sos',
    number: 2,
    phase: 'A',
    title: 'Emergency SOS',
    tagline: 'One press, everyone who matters is notified',
    description: 'Sends your live GPS location and an alert to every family member and emergency contact the moment help is needed — no typing, no searching for a number.',
    status: 'live',
    pattern: 'sos',
    props: {
      heading: 'Need Help Now',
      subtext: 'Press and hold to send your location to family instantly.',
      buttonLabel: 'SOS',
      notified: ['Priya (Daughter)', 'Raj (Son)', 'Dr. Mehta'],
    },
  },
  {
    slug: 'family-call',
    number: 3,
    phase: 'A',
    title: 'Family Call',
    tagline: 'One tap to reach the people you trust',
    description: 'A short list of saved family members, each with a big photo and name — tap once to call, no dial pad, no contact search.',
    status: 'live',
    pattern: 'contact-list',
    props: {
      contacts: [
        { name: 'Priya Sharma', relation: 'Daughter', initial: 'P' },
        { name: 'Raj Sharma', relation: 'Son', initial: 'R' },
        { name: 'Dr. Anjali Mehta', relation: 'Family doctor', initial: 'A' },
      ],
    },
  },
  {
    slug: 'emergency-contacts',
    number: 4,
    phase: 'A',
    title: 'Emergency contacts management',
    tagline: 'Family keeps the safety list up to date',
    description: 'Family members can add, reorder, and remove who gets notified during an SOS — the elder never has to manage this list themselves.',
    status: 'live',
    pattern: 'item-list',
    props: {
      icon: 'Users',
      addLabel: 'Add contact',
      items: [
        { title: 'Priya Sharma', detail: 'Daughter · Primary contact', badge: 'Notify on SOS', badgeVariant: 'success' },
        { title: 'Raj Sharma', detail: 'Son', badge: 'Notify on SOS', badgeVariant: 'success' },
        { title: 'Dr. Anjali Mehta', detail: 'Family doctor', badge: 'Notify on SOS', badgeVariant: 'success' },
      ],
    },
  },
  {
    slug: 'elder-invite',
    number: 5,
    phase: 'A',
    title: 'Elder invite / link flow',
    tagline: 'Family links an elder, elder accepts',
    description: 'A family member invites an elder by email; the elder sees a pending request the next time they sign in and accepts it themselves — no shared passwords, no admin in the middle.',
    status: 'live',
    pattern: 'item-list',
    props: {
      icon: 'UserPlus',
      addLabel: 'Send invite',
      items: [
        { title: 'Kamala Iyer', detail: 'Invited as your elder · Daughter', badge: 'Pending', badgeVariant: 'accent' },
        { title: 'Suresh Iyer', detail: 'Linked · Son', badge: 'Accepted', badgeVariant: 'success' },
      ],
    },
  },
  {
    slug: 'admin-overview',
    number: 6,
    phase: 'A',
    title: 'Admin: users & SOS feed',
    tagline: 'One place to see everyone, and every alert',
    description: 'A platform-wide list of every account and a live feed of every SOS event, most recent first — the operational nerve center for the team running EC.',
    status: 'live',
    pattern: 'table',
    props: {
      columns: ['Name', 'Role', 'Joined'],
      rows: [
        { cells: ['Kamala Iyer', 'Elder', '2 days ago'], badge: { label: 'Elder', variant: 'default' } },
        { cells: ['Priya Sharma', 'Family', '2 days ago'], badge: { label: 'Family', variant: 'accent' } },
        { cells: ['Dr. Anjali Mehta', 'Provider', '1 day ago'], badge: { label: 'Provider', variant: 'success' } },
      ],
    },
  },
  {
    slug: 'ambulance-quick-dial',
    number: 7,
    phase: 'A',
    title: 'Ambulance quick-dial',
    tagline: 'One tap, no searching for a number',
    description: 'A dedicated, always-visible button that dials the ambulance directly — separate from the general SOS flow, for when the need is specifically medical and urgent.',
    status: 'live',
    pattern: 'tile-grid',
    props: {
      tiles: [{ icon: 'Ambulance', label: 'Call Ambulance', sublabel: 'Dials 108 directly', accent: 'danger' }],
    },
  },
  {
    slug: 'local-directory',
    number: 8,
    phase: 'A2',
    title: 'Local directory',
    tagline: 'Every trusted local business, in one list',
    description: 'A browsable, searchable directory of shops, clinics, and services in the elder\'s neighborhood — built by the community, verified by admins.',
    status: 'planned',
    pattern: 'directory',
    props: {
      listings: [
        { icon: 'Building2', name: 'Sunrise Pharmacy', category: 'Pharmacy', rating: '4.8', distance: '0.4 km' },
        { icon: 'Stethoscope', name: 'City Care Clinic', category: 'General Physician', rating: '4.6', distance: '1.1 km' },
        { icon: 'Wrench', name: 'Ramesh Electricals', category: 'Electrician', rating: '4.9', distance: '0.7 km' },
        { icon: 'ShoppingCart', name: 'Green Basket Grocers', category: 'Groceries', rating: '4.5', distance: '0.3 km' },
      ],
    },
  },
  {
    slug: 'neighbor-chat',
    number: 9,
    phase: 'A2',
    title: 'Neighbor-to-neighbor chat',
    tagline: 'A safe, moderated way to stay connected nearby',
    description: 'Chat scoped to your own neighborhood, not the open internet — easier to moderate, and genuinely useful for coordinating with people who live close by.',
    status: 'planned',
    pattern: 'chat',
    props: {
      channelName: 'Green Meadows Society',
      messages: [
        { from: 'Lakshmi', text: 'Does anyone know a good plumber nearby?' },
        { from: 'You', text: 'Ramesh Electricals does plumbing too, very reliable!', self: true },
        { from: 'Lakshmi', text: 'Thank you, will call them.' },
      ],
    },
  },
  {
    slug: 'residents-association',
    number: 10,
    phase: 'A2',
    title: 'Residents Association',
    tagline: 'Notices and its own local directory',
    description: 'Each neighborhood gets its own notice board for official announcements, plus a directory scoped just to that society — built fresh inside EC, no external RWA system needed.',
    status: 'planned',
    pattern: 'item-list',
    props: {
      icon: 'Megaphone',
      addLabel: 'Post notice',
      items: [
        { title: 'Water supply maintenance', detail: 'Tomorrow, 10 AM – 2 PM', badge: 'This week', badgeVariant: 'accent' },
        { title: 'Society AGM', detail: 'Saturday, 6 PM, Community Hall', badge: 'Upcoming', badgeVariant: 'default' },
      ],
    },
  },
  {
    slug: 'local-service-registration',
    number: 11,
    phase: 'A2',
    title: 'Local service registration',
    tagline: 'Plumbers, electricians, and more — listed and findable',
    description: 'Local tradespeople register their service once, and every elder and family member in the area can find and call them from the local directory.',
    status: 'planned',
    pattern: 'item-list',
    props: {
      icon: 'Wrench',
      addLabel: 'Register a service',
      items: [
        { title: 'Ramesh Electricals', detail: 'Electrician · Verified', badge: 'Verified', badgeVariant: 'success' },
        { title: 'Suresh Plumbing Works', detail: 'Plumber · Pending review', badge: 'Pending', badgeVariant: 'accent' },
      ],
    },
  },
  {
    slug: 'consolidator-connect',
    number: 12,
    phase: 'A2',
    title: 'Consolidator connect',
    tagline: 'One tap into Porter, Swiggy, Zomato & more',
    description: 'A smart referral into the apps elders and families already trust — EC opens the partner app with the address and request pre-filled, so nobody re-types anything.',
    status: 'planned',
    pattern: 'deep-link',
    props: {
      partners: [
        { name: 'Porter', blurb: 'Movers & packers, on demand', color: '#4E5D78' },
        { name: 'Swiggy', blurb: 'Food delivery', color: '#FC8019' },
        { name: 'Urban Company', blurb: 'Home services at your door', color: '#3A3A3A' },
        { name: 'Instamart', blurb: 'Groceries in minutes', color: '#FF6B57' },
      ],
    },
  },
  {
    slug: 'medicine-reminders',
    number: 13,
    phase: 'B',
    title: 'Medicine reminders',
    tagline: 'Never miss a dose, without a fuss',
    description: 'Family sets up the schedule once; the elder gets a simple reminder and confirms with one tap, and a missed dose quietly alerts the family.',
    status: 'planned',
    pattern: 'item-list',
    props: {
      icon: 'Pill',
      addLabel: 'Add medicine',
      items: [
        { title: 'Metformin 500mg', detail: 'After breakfast, 8:00 AM', badge: 'Taken', badgeVariant: 'success' },
        { title: 'Amlodipine 5mg', detail: 'After dinner, 8:00 PM', badge: 'Upcoming', badgeVariant: 'default' },
        { title: 'Vitamin D3', detail: 'Once a week, Sunday', badge: 'Missed yesterday', badgeVariant: 'danger' },
      ],
    },
  },
  {
    slug: 'appointments',
    number: 14,
    phase: 'B',
    title: 'Appointments',
    tagline: 'Every doctor visit, in one calendar',
    description: 'A simple, date-forward view of every upcoming appointment — who, where, and when — visible to both the elder and their family.',
    status: 'planned',
    pattern: 'calendar',
    props: {
      appointments: [
        { day: '14', month: 'Aug', title: 'Dr. Anjali Mehta — Cardiology', time: '11:00 AM', place: 'City Care Clinic' },
        { day: '22', month: 'Aug', title: 'Eye check-up', time: '4:30 PM', place: 'Sunrise Eye Hospital' },
      ],
    },
  },
  {
    slug: 'health-notes',
    number: 15,
    phase: 'B',
    title: 'Health notes',
    tagline: 'A shared, simple health journal',
    description: 'Short notes about how the elder is doing, added by family or the elder themselves — no medical jargon required, just a running record everyone can see.',
    status: 'planned',
    pattern: 'item-list',
    props: {
      icon: 'FileText',
      addLabel: 'Add note',
      items: [
        { title: 'Feeling much better today', detail: 'Added by Kamala · 2 days ago' },
        { title: 'Slight cough, keeping an eye on it', detail: 'Added by Priya · 5 days ago' },
      ],
    },
  },
  {
    slug: 'food-assistance',
    number: 16,
    phase: 'B',
    title: 'Food / meal assistance',
    tagline: 'Family fulfills a meal request, remotely',
    description: 'The elder taps "I need food" and family sees the request instantly — they can arrange a delivery or a home-cooked meal without a phone call.',
    status: 'planned',
    pattern: 'item-list',
    props: {
      icon: 'Utensils',
      addLabel: 'New request',
      items: [
        { title: 'Lunch requested', detail: 'Kamala · 12:30 PM today', badge: 'Fulfilled', badgeVariant: 'success' },
        { title: 'Dinner reminder', detail: 'Daily, 7:30 PM', badge: 'Recurring', badgeVariant: 'default' },
      ],
    },
  },
  {
    slug: 'caregiver-dashboard',
    number: 17,
    phase: 'B',
    title: 'Caregiver dashboard',
    tagline: 'Everything at a glance, for peace of mind',
    description: 'Medication adherence, upcoming appointments, and recent activity — one screen that tells family "is everything okay?" without having to ask.',
    status: 'planned',
    pattern: 'stats',
    props: {
      stats: [
        { icon: 'Pill', label: 'Medicines taken today', value: '2 of 3', tone: 'primary' },
        { icon: 'Calendar', label: 'Appointments this week', value: '1', tone: 'accent' },
        { icon: 'ShieldCheck', label: 'SOS alerts', value: 'All clear', tone: 'success' },
      ],
      chartBars: [40, 70, 55, 90, 60, 80, 75],
    },
  },
  {
    slug: 'service-request-workflow',
    number: 18,
    phase: 'C',
    title: 'Ambulance & local services — full workflow',
    tagline: 'From a tap to an assigned provider',
    description: 'What starts as a directory listing graduates into a real request-and-assignment workflow — track status from requested, to assigned, to completed.',
    status: 'planned',
    pattern: 'queue',
    props: {
      requests: [
        { title: 'Ambulance requested', detail: 'Kamala Iyer · Green Meadows Society', eta: 'Requested 2 min ago', status: 'Assigning' },
        { title: 'Electrician requested', detail: 'Ramesh Electricals · Fan repair', eta: 'ETA 40 minutes', status: 'Assigned' },
      ],
    },
  },
  {
    slug: 'provider-portal',
    number: 19,
    phase: 'C',
    title: 'Service Provider portal',
    tagline: 'Where local providers manage incoming work',
    description: 'Providers see incoming requests as they arrive and respond with one tap — accept, decline, and update status, all from a dedicated portal.',
    status: 'planned',
    pattern: 'queue',
    props: {
      requests: [
        { title: 'New request: Home nursing visit', detail: 'Kamala Iyer · Blood pressure check', eta: 'Requested 5 min ago', status: 'New' },
        { title: 'New request: Plumbing', detail: 'Suresh Iyer · Leaking tap', eta: 'Requested 20 min ago', status: 'New' },
      ],
    },
  },
  {
    slug: 'provider-verification',
    number: 20,
    phase: 'C',
    title: 'Admin: provider verification',
    tagline: 'Every provider vetted before they go live',
    description: 'A review queue for new provider sign-ups — admins verify credentials and category before a provider can receive real requests.',
    status: 'planned',
    pattern: 'table',
    props: {
      columns: ['Provider', 'Category', 'Submitted'],
      rows: [
        { cells: ['City Care Clinic', 'Healthcare', '1 day ago'], badge: { label: 'Pending', variant: 'accent' } },
        { cells: ['Ramesh Electricals', 'Home services', '3 days ago'], badge: { label: 'Verified', variant: 'success' } },
      ],
    },
  },
  {
    slug: 'voice-assistant',
    number: 21,
    phase: 'D',
    title: 'Voice Assistant',
    tagline: 'Just ask — no menus, no typing',
    description: 'Powered by Claude — the elder speaks naturally and EC understands the intent, whether that\'s calling someone, checking medicines, or asking a question.',
    status: 'planned',
    pattern: 'voice',
    props: {
      prompt: 'When is my next doctor appointment?',
      response: 'You have an appointment with Dr. Anjali Mehta on August 14th at 11:00 AM at City Care Clinic.',
    },
  },
  {
    slug: 'richer-chat-social',
    number: 22,
    phase: 'D',
    title: 'Richer chat & social',
    tagline: 'Photos, moderation, and a friendlier feel',
    description: 'Neighbor chat grows up — share a photo, moderate what needs moderating, and make the whole thing feel more like a community than a message board.',
    status: 'planned',
    pattern: 'chat',
    props: {
      channelName: 'Green Meadows Society',
      messages: [
        { from: 'Lakshmi', text: 'Beautiful morning for a walk in the garden!' },
        { from: 'You', text: 'Agreed, saw you there earlier 😊', self: true },
      ],
    },
  },
  {
    slug: 'admin-analytics',
    number: 23,
    phase: 'D',
    title: 'Admin analytics',
    tagline: 'How the whole platform is really doing',
    description: 'Usage trends, response times, and adoption across every neighborhood — the dashboard that tells the team where to focus next.',
    status: 'planned',
    pattern: 'stats',
    props: {
      stats: [
        { icon: 'Users', label: 'Active elders', value: '1,204', tone: 'primary' },
        { icon: 'ShieldCheck', label: 'SOS response time (avg)', value: '3.2 min', tone: 'success' },
        { icon: 'BarChart3', label: 'Weekly growth', value: '+8.4%', tone: 'accent' },
      ],
      chartBars: [30, 45, 40, 60, 55, 75, 85],
    },
  },
  {
    slug: 'accessibility-audit',
    number: 24,
    phase: 'D',
    title: 'Accessibility audit',
    tagline: 'Verified elder-friendly, not just assumed',
    description: 'A full pass across every breakpoint and input method — large enough text, high enough contrast, touch targets sized for less steady hands.',
    status: 'planned',
    pattern: 'checklist',
    props: {
      items: [
        { label: 'Touch targets ≥ 48px', pass: true, detail: 'Verified across all elder-facing screens' },
        { label: 'Text contrast ratio ≥ 4.5:1', pass: true, detail: 'Checked against WCAG AA' },
        { label: 'Works with screen readers', pass: false, detail: 'In progress — voice assistant screens next' },
      ],
    },
  },
  {
    slug: 'mobile-app',
    number: 25,
    phase: 'E',
    title: 'Native mobile app',
    tagline: 'A trimmed companion, not a full port',
    description: 'The Android app deliberately covers only the highest-frequency elder actions — SOS, calling family, medicine, voice — everything else stays on the comprehensive web app.',
    status: 'live',
    pattern: 'phone-frame',
    props: {
      tiles: [
        { icon: 'Phone', label: 'Call Family' },
        { icon: 'Grid3x3', label: 'Dial Pad' },
        { icon: 'Pill', label: 'Medicine' },
        { icon: 'Mic', label: 'Speak to EC' },
      ],
    },
  },
  {
    slug: 'large-dial-pad',
    number: 26,
    phase: 'A',
    title: 'Large dial pad',
    tagline: 'A phone keypad, sized for real use',
    description: 'Big, unmistakable number keys for dialing any number directly — built for the Android app, where native calling matters most.',
    status: 'live',
    pattern: 'phone-frame',
    props: {
      tiles: [
        { icon: 'Grid3x3', label: '1 · 2 · 3' },
        { icon: 'Grid3x3', label: '4 · 5 · 6' },
        { icon: 'Grid3x3', label: '7 · 8 · 9' },
        { icon: 'Phone', label: 'Call' },
      ],
    },
  },
  {
    slug: 'personal-care-directory',
    number: 27,
    phase: 'A2',
    title: 'Personal care & grooming',
    tagline: 'Trusted help, close to home',
    description: 'A dedicated category in the local directory for personal care and grooming providers — barbers, salons, and in-home care specialists.',
    status: 'planned',
    pattern: 'directory',
    props: {
      listings: [
        { icon: 'Users', name: 'Grace Home Salon', category: 'In-home grooming', rating: '4.7', distance: '0.6 km' },
        { icon: 'Users', name: 'Comfort Care Services', category: 'Personal care aide', rating: '4.9', distance: '1.2 km' },
      ],
    },
  },
  {
    slug: 'home-management-services',
    number: 28,
    phase: 'A2',
    title: 'Home management services',
    tagline: 'Cleaning, nursing, and maid services — verified',
    description: 'Book trusted home help through Urban Company or a verified local listing, all from the same directory the elder already knows.',
    status: 'planned',
    pattern: 'directory',
    props: {
      listings: [
        { icon: 'Home', name: 'Urban Company — Cleaning', category: 'Home cleaning', rating: '4.6', distance: 'On demand' },
        { icon: 'Stethoscope', name: 'CareNurse Home Visits', category: 'Home nursing', rating: '4.8', distance: '0.9 km' },
      ],
    },
  },
  {
    slug: 'cab-travel-booking',
    number: 29,
    phase: 'A2',
    title: 'Cab & travel booking',
    tagline: 'A ride, one tap away',
    description: 'Deep-links straight into Ola or Uber with the destination pre-filled — no separate app hunting required.',
    status: 'planned',
    pattern: 'deep-link',
    props: {
      partners: [
        { name: 'Ola', blurb: 'Book a cab now', color: '#B6D633' },
        { name: 'Uber', blurb: 'Ride in minutes', color: '#000000' },
      ],
    },
  },
  {
    slug: 'shopping-groceries',
    number: 30,
    phase: 'A2',
    title: 'Shopping & groceries',
    tagline: 'Everyday essentials, delivered',
    description: 'Deep-links into grocery and general ecommerce delivery partners, so restocking essentials never requires leaving home.',
    status: 'planned',
    pattern: 'deep-link',
    props: {
      partners: [
        { name: 'Dunzo', blurb: 'Groceries & essentials', color: '#00D290' },
        { name: 'Instamart', blurb: 'Groceries in minutes', color: '#FF6B57' },
      ],
    },
  },
  {
    slug: 'sos-healthcare-routing',
    number: 31,
    phase: 'C',
    title: 'SOS → healthcare provider routing',
    tagline: 'Not just family — real medical response',
    description: 'Once a registered provider network exists, an SOS can route directly to a nearby healthcare provider, not only to family and emergency contacts.',
    status: 'planned',
    pattern: 'sos',
    props: {
      heading: 'Emergency Alert Sent',
      subtext: 'Your location and a request for help have been sent.',
      buttonLabel: 'SOS',
      notified: ['Priya (Daughter)', 'City Care Clinic', 'Ambulance dispatch'],
    },
  },
  {
    slug: 'diagnostics-pharma',
    number: 32,
    phase: 'C',
    title: 'Diagnostics, pharmacy & doctor integrations',
    tagline: 'Practo, Thyrocare, and PharmEasy, one tap away',
    description: 'Book a diagnostic test, order medicine, or find a doctor through named, trusted integrations — surfaced right in the local directory.',
    status: 'planned',
    pattern: 'directory',
    props: {
      listings: [
        { icon: 'Hospital', name: 'Practo — Find a Doctor', category: 'Doctor discovery', rating: '4.7', distance: 'Online' },
        { icon: 'Building2', name: 'Thyrocare', category: 'Diagnostics & lab tests', rating: '4.6', distance: '2.1 km' },
        { icon: 'Pill', name: 'PharmEasy', category: 'Pharmacy delivery', rating: '4.5', distance: 'Online' },
      ],
    },
  },
  {
    slug: 'video-calling',
    number: 33,
    phase: 'D',
    title: 'Video calling',
    tagline: 'See each other, not just hear',
    description: 'Chat grows to include video calling — the same one-tap simplicity as Family Call, with a face on the other end.',
    status: 'planned',
    pattern: 'chat',
    props: {
      channelName: 'Video call with Priya',
      hasVideo: true,
      messages: [
        { from: 'Priya', text: 'Calling you now, one sec!' },
        { from: 'You', text: 'Okay, I\'m ready 😊', self: true },
      ],
    },
  },
  {
    slug: 'social-entertainment',
    number: 34,
    phase: 'D',
    title: 'Social & entertainment discovery',
    tagline: 'Local events, movies, and gifting',
    description: 'Discover what\'s happening nearby — community events, movie showtimes, and an easy way to send a gift to someone who matters.',
    status: 'planned',
    pattern: 'media',
    props: {
      cards: [
        { icon: 'Film', title: 'Evening movie showtimes', subtitle: 'PVR Cinemas, 3 nearby screenings' },
        { icon: 'Camera', title: 'Society Diwali celebration', subtitle: 'Green Meadows, this Saturday' },
        { icon: 'Gift', title: 'Send a gift to Kamala', subtitle: 'Flowers, sweets & more' },
      ],
    },
  },
  {
    slug: 'banking-access',
    number: 35,
    phase: 'F',
    title: 'Banking & Paytm access',
    tagline: 'A simple view into money that matters',
    description: 'A read-first view of balance and recent activity, plus quick UPI actions — needs a real payment-partner decision before this goes further than a mockup.',
    status: 'planned',
    pattern: 'finance',
    props: {
      balance: '₹42,180',
      transactions: [
        { name: 'Pension credit', amount: '+₹18,000', in: true },
        { name: 'Electricity bill', amount: '-₹1,240', in: false },
        { name: 'From Priya (daughter)', amount: '+₹5,000', in: true },
      ],
    },
  },
  {
    slug: 'home-automation',
    number: 36,
    phase: 'F',
    title: 'Home automation control',
    tagline: 'Lights, robots, and Google Home — one screen',
    description: 'Control smart-home devices without a separate app or a voice command to remember — a simple grid of what\'s on and what\'s off.',
    status: 'planned',
    pattern: 'toggle-grid',
    props: {
      devices: [
        { icon: 'Lightbulb', label: 'Living room lights', on: true },
        { icon: 'Fan', label: 'Bedroom fan', on: false },
        { icon: 'Home', label: 'Front door lock', on: true },
        { icon: 'Grid3x3', label: 'Robot vacuum', on: false },
      ],
    },
  },
  {
    slug: 'music-radio',
    number: 37,
    phase: 'F',
    title: 'Music & radio player',
    tagline: 'Favorite stations, one tap to play',
    description: 'A simple, large-button player for music and radio — no complex library to browse, just the stations already loved.',
    status: 'planned',
    pattern: 'media',
    props: {
      cards: [
        { icon: 'Music', title: 'All India Radio — Vividh Bharati', subtitle: 'Now playing' },
        { icon: 'Music', title: 'Classical Favorites', subtitle: 'Saved playlist' },
      ],
    },
  },
  {
    slug: 'money-transfer',
    number: 38,
    phase: 'F',
    title: 'Money transfer from relatives',
    tagline: 'Family sends, elder receives — simply',
    description: 'A dedicated, simple flow for family to send money directly, separate from general banking — needs the same payment-partner decision as banking access.',
    status: 'planned',
    pattern: 'finance',
    props: {
      balance: '₹42,180',
      transactions: [
        { name: 'From Raj (son)', amount: '+₹10,000', in: true },
        { name: 'From Priya (daughter)', amount: '+₹5,000', in: true },
      ],
    },
  },
];

export const ICON_MAP = {
  Home,
  Phone,
  Users,
  UserPlus,
  ShieldCheck,
  Ambulance,
  MapPin,
  MessageCircle,
  Megaphone,
  Wrench,
  Truck,
  Pill,
  Calendar,
  FileText,
  Utensils,
  LayoutDashboard,
  ClipboardCheck,
  Building2,
  Mic,
  Video,
  BarChart3,
  Accessibility,
  Smartphone,
  Grid3x3,
  Stethoscope,
  Car,
  ShoppingCart,
  Hospital,
  Film,
  Landmark,
  Lightbulb,
  Music,
  Send,
  Fan,
  Camera,
  Gift,
};
